package dam;
// Generated 25-nov-2020 13:53:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private String idcargo;
     private String nombre;
     private int sueldoMin;
     private int sueldoMax;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Cargo() {
    }

	
    public Cargo(String idcargo, String nombre, int sueldoMin, int sueldoMax) {
        this.idcargo = idcargo;
        this.nombre = nombre;
        this.sueldoMin = sueldoMin;
        this.sueldoMax = sueldoMax;
    }
    public Cargo(String idcargo, String nombre, int sueldoMin, int sueldoMax, Set<Empleado> empleados) {
       this.idcargo = idcargo;
       this.nombre = nombre;
       this.sueldoMin = sueldoMin;
       this.sueldoMax = sueldoMax;
       this.empleados = empleados;
    }
   
    public String getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(String idcargo) {
        this.idcargo = idcargo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getSueldoMin() {
        return this.sueldoMin;
    }
    
    public void setSueldoMin(int sueldoMin) {
        this.sueldoMin = sueldoMin;
    }
    public int getSueldoMax() {
        return this.sueldoMax;
    }
    
    public void setSueldoMax(int sueldoMax) {
        this.sueldoMax = sueldoMax;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


