package dam;
// Generated 25-nov-2020 13:53:29 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String idempleado;
     private Cargo cargo;
     private String apellido;
     private String nombre;
     private Date fecingreso;
     private String email;
     private String telefono;
     private Integer iddepartamento;
     private int sueldo;
     private Integer comision;
     private String jefe;
     private Usuario usuario;

    public Empleado() {
    }

	
    public Empleado(String idempleado, String apellido, String nombre, Date fecingreso, int sueldo) {
        this.idempleado = idempleado;
        this.apellido = apellido;
        this.nombre = nombre;
        this.fecingreso = fecingreso;
        this.sueldo = sueldo;
    }
    public Empleado(String idempleado, Cargo cargo, String apellido, String nombre, Date fecingreso, String email, String telefono, Integer iddepartamento, int sueldo, Integer comision, String jefe, Usuario usuario) {
       this.idempleado = idempleado;
       this.cargo = cargo;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fecingreso = fecingreso;
       this.email = email;
       this.telefono = telefono;
       this.iddepartamento = iddepartamento;
       this.sueldo = sueldo;
       this.comision = comision;
       this.jefe = jefe;
       this.usuario = usuario;
    }
   
    public String getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(String idempleado) {
        this.idempleado = idempleado;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecingreso() {
        return this.fecingreso;
    }
    
    public void setFecingreso(Date fecingreso) {
        this.fecingreso = fecingreso;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(Integer iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public int getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(int sueldo) {
        this.sueldo = sueldo;
    }
    public Integer getComision() {
        return this.comision;
    }
    
    public void setComision(Integer comision) {
        this.comision = comision;
    }
    public String getJefe() {
        return this.jefe;
    }
    
    public void setJefe(String jefe) {
        this.jefe = jefe;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


