package dam;
// Generated 25-nov-2020 13:53:29 by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idempleado;
     private Empleado empleado;
     private String usuario;
     private String clave;
     private Integer estado;

    public Usuario() {
    }

	
    public Usuario(Empleado empleado, String usuario, String clave) {
        this.empleado = empleado;
        this.usuario = usuario;
        this.clave = clave;
    }
    public Usuario(Empleado empleado, String usuario, String clave, Integer estado) {
       this.empleado = empleado;
       this.usuario = usuario;
       this.clave = clave;
       this.estado = estado;
    }
   
    public String getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(String idempleado) {
        this.idempleado = idempleado;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


