package dam;
// Generated 11-nov-2020 11:57:25 by Hibernate Tools 3.6.0

import java.util.List;
import java.util.Scanner;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import singleton.HibernateUtil;




/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer id;
     private Categorias categorias;
     private String nombreProducto;
     private Float precio;

    public Productos() {
    }

    public Productos(Categorias categorias, String nombreProducto, Float precio) {
       this.categorias = categorias;
       this.nombreProducto = nombreProducto;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }

    public static void obtenerYModificarProducto(){
        
         SessionFactory sessionFactory =HibernateUtil.getSessionFactory() ;
         Session session = sessionFactory.openSession();
         int id_buscar = 2;
         float nuevoPrecio = 3f;
         Productos producto = (Productos) session.get(Productos.class,id_buscar);
         
         if(producto != null){
             producto.setPrecio(nuevoPrecio);
             Transaction tx = session.beginTransaction();
             session.update(producto);
             tx.commit();
         }
        
    }
    
    public static void obtenerTodo(){
         SessionFactory sessionFactory =HibernateUtil.getSessionFactory() ;
         Session session = sessionFactory.openSession();
                Query q = session.createQuery("SELECT p FROM Productos p");
                List<Productos> lista = q.list();
                for(Productos p : lista){
                    System.out.println("id:"+p.id+" nombre:"+p.nombreProducto+" precio:"+p.precio);
                }
                session.close();
    }
    public static void consultarPrecio(){
        
        Scanner sc= new Scanner(System.in);
        System.out.println("De que producto quieres consultar el precio?");
        String nombreprod=sc.nextLine();
        
        SessionFactory sessionFactory =HibernateUtil.getSessionFactory() ;
         Session session = sessionFactory.openSession();
         Query q=session.createQuery("SELECT p.precio FROM Productos p WHERE p.nombreProducto=:nombreprod");
         q.setParameter("nombreprod",nombreprod);
         
         
         float f =(float) q.uniqueResult();
         
          System.out.println("precio:+"+f);
          session.close();
          sc.close();
                
        
    }



}


